{% set name = "fancy-collections" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace("-", "_") }}-{{ version }}.tar.gz
  sha256: fd824399ee852e21d3b908088ce996a6930907f6cb504ed291fdf665e172146e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --ignore-installed
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy
    - scipy
    - pandas
    - sliceable-dict

test:
  imports:
    - fancy_collections
    - fancy_collections.core
    - fancy_collections.formatting
    - fancy_collections.lib

about:
  home: https://github.com/palmb/fancy-collections/
  summary: Useful classes to store data in a structured way
  description: |
    This package provide some useful classes to store data in a structured way.
    Up to now mostly advanced dictionaries are provided.
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bernt-matthias
